# Generated by Django 3.1.3 on 2020-11-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='genre',
        ),
    ]
